In [ ]:
#PRN : 25070123068 Name:Lakshya Sonawane
#Title : Data Binning and Data Formatting using Python

In [1]:
import pandas as pd
import numpy as np

data = {
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15]
}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [3]:
#Data Binning
bins1 = [0,10000,30000,60000]
labels1 = ['Low','Medium','High']

df['Price_Category'] = pd.cut(df['Price'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_Sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet  30000          35         Medium
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [6]:
#Binning Units Sold
bins2 = [0,30,60,100]
labels2 = ['Low','Medium','High']

df['Units_Sold_Category'] = pd.cut(df['Units_Sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      Laptop  55000          25           High                 Low
1      Mobile  20000          60         Medium              Medium
2      Tablet  30000          35         Medium              Medium
3  Headphones   2000          80            Low                High
4  Smartwatch   8000          50            Low              Medium
5      Camera  45000          15           High                 Low

In [8]:
#Data Formatting
#Convert Data Type
print(df.dtypes)
df['Units_Sold'] = df['Units_Sold'].astype(float)
print(df.dtypes)

Product                  object
Price                     int64
Units_Sold                int64
Price_Category         category
Units_Sold_Category    category
dtype: object
Product                  object
Price                     int64
Units_Sold              float64
Price_Category         category
Units_Sold_Category    category
dtype: object

In [10]:
#Convert Text to Uppercase
df['Product'] = df['Product'].str.upper()
df

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      LAPTOP  55000        25.0           High                 Low
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
5      CAMERA  45000        15.0           High                 Low

In [11]:
#Rounding values
df['Price'].round(2)
print(df)

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      LAPTOP  55000        25.0           High                 Low
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
5      CAMERA  45000        15.0           High                 Low

In [12]:
#Additional Operations
#Sort Data
sorted_df= df.sort_values(by='Price')
print(df)

      Product  Price  Units_Sold Price_Category Units_Sold_Category
0      LAPTOP  55000        25.0           High                 Low
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
5      CAMERA  45000        15.0           High                 Low

In [13]:
#Additional Operations
#Sort Data
df.sort_values(by='Price' , inplace=True)
df

      Product  Price  Units_Sold Price_Category Units_Sold_Category
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
5      CAMERA  45000        15.0           High                 Low
0      LAPTOP  55000        25.0           High                 Low

In [17]:
#Additional Operations
#Sort Data
df.sort_values(by='Price' ,ascending=False)
df

      Product  Price  Units_Sold Price_Category Units_Sold_Category
3  HEADPHONES   2000        80.0            Low                High
4  SMARTWATCH   8000        50.0            Low              Medium
1      MOBILE  20000        60.0         Medium              Medium
2      TABLET  30000        35.0         Medium              Medium
5      CAMERA  45000        15.0           High                 Low
0      LAPTOP  55000        25.0           High                 Low

In [19]:
#Display Unique Values
print(df['Price_Category'].unique())

['Low', 'Medium', 'High']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [21]:
import pandas as pd
import numpy as np
data = {
    'Order_ID': ['01','02','03','04','05','06','07','08'],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,25,60,35,20,50,28],
    'Distance_km':[5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
print(df)

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [22]:
#Binning Order Value
bins = [0,200,400,700]
labels = ['Low','Medium','High']
df['Order_Value_Category'] = pd.cut(df['Order_Value'],bins=bins,labels=labels)
df

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category
0       01          250             30            5               Medium
1       02          450             45            8                 High
2       03          120             25            3                  Low
3       04          600             60           10                 High
4       05          300             35            6               Medium
5       06          150             20            2                  Low
6       07          500             50            9                 High
7       08          220             28            4               Medium

In [23]:
#Binning Delivery Time
bins2 = [0,30,45,70]
labels2 = ['Fast','Normal','Slow']
df['Delivery_Time_Category'] = pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Time_Category
0,01,250,30,5,Medium,Fast
1,02,450,45,8,High,Normal
2,03,120,25,3,Low,Fast
3,04,600,60,10,High,Slow
4,05,300,35,6,Medium,Normal
5,06,150,20,2,Low,Fast
6,07,500,50,9,High,Slow
7,08,220,28,4,Medium,Fast

In [38]:
#Binning Distance km
bins3 = [2.5,5,7.5,10]
labels3=['Short','Medium','Long']
df['Distance_Category'] = pd.cut(df['Distance_km'],bins=bins3,labels=labels3)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Time_Category,Distance_Category
0,01,250,30,5,Medium,Fast,Short
1,02,450,45,8,High,Normal,Long
2,03,120,25,3,Low,Fast,Short
3,04,600,60,10,High,Slow,Long
4,05,300,35,6,Medium,Normal,Medium
5,06,150,20,2,Low,Fast,NaN
6,07,500,50,9,High,Slow,Long
7,08,220,28,4,Medium,Fast,Short

In [37]:
#Count of categories
print(df['Order_Value_Category'].value_counts())
df

Order_Value_Category
Medium    3
High      3
Low       2
Name: count, dtype: int64

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Time_Category,Distance_Category
0,01,250,30,5,Medium,Fast,Short
1,02,450,45,8,High,Normal,Long
2,03,120,25,3,Low,Fast,Short
3,04,600,60,10,High,Slow,Long
4,05,300,35,6,Medium,Normal,Medium
5,06,150,20,2,Low,Fast,NaN
6,07,500,50,9,High,Slow,Long
7,08,220,28,4,Medium,Fast,Short

In [39]:
#Sorting
print(df.sort_values(by='Order_Value'))
df

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Value_Category  \
2       03          120             25            3                  Low
5       06          150             20            2                  Low
7       08          220             28            4               Medium
0       01          250             30            5               Medium
4       05          300             35            6               Medium
1       02          450             45            8                 High
6       07          500             50            9                 High
3       04          600             60           10                 High

  Delivery_Time_Category Distance_Category
2                   Fast             Short
5                   Fast               NaN
7                   Fast             Short
0                   Fast             Short
4                 Normal            Medium
1                 Normal              Long
6                   Slow              Long
3                   Slow              Long

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Time_Category,Distance_Category
0,01,250,30,5,Medium,Fast,Short
1,02,450,45,8,High,Normal,Long
2,03,120,25,3,Low,Fast,Short
3,04,600,60,10,High,Slow,Long
4,05,300,35,6,Medium,Normal,Medium
5,06,150,20,2,Low,Fast,NaN
6,07,500,50,9,High,Slow,Long
7,08,220,28,4,Medium,Fast,Short

In [41]:
#Convert Order_ID to uppercase
df['Order_ID'] = df['Order_ID'].str.upper()
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Time_Category,Distance_Category
0,01,250,30,5,Medium,Fast,Short
1,02,450,45,8,High,Normal,Long
2,03,120,25,3,Low,Fast,Short
3,04,600,60,10,High,Slow,Long
4,05,300,35,6,Medium,Normal,Medium
5,06,150,20,2,Low,Fast,NaN
6,07,500,50,9,High,Slow,Long
7,08,220,28,4,Medium,Fast,Short

In [43]:
#Sort Data
df.sort_values(by='Delivery_Time' ,ascending=False)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Value_Category,Delivery_Time_Category,Distance_Category
0,01,250,30,5,Medium,Fast,Short
1,02,450,45,8,High,Normal,Long
2,03,120,25,3,Low,Fast,Short
3,04,600,60,10,High,Slow,Long
4,05,300,35,6,Medium,Normal,Medium
5,06,150,20,2,Low,Fast,NaN
6,07,500,50,9,High,Slow,Long
7,08,220,28,4,Medium,Fast,Short